# Generated by Django 4.0.5 on 2022-06-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
